micronaut:
  application:
    name: micronaut-flyway-graal

datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/users'
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret
    schema-generate: NONE
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
---
endpoints:
  flyway:
    enabled: true
    sensitive: false
